/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import commands.Command;
import commands.CommandTracker;
import commands.interfaces.ICommandBehavior;
import commands.vehicleManagement.AddService;
import commands.vehicleManagement.RemoveService;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.DefaultListModel;
import models.Car;
import models.Service;

/**
 *
 * @author FairyMental
 */
public class ManageServiceHistoryPanel extends javax.swing.JPanel {

    Car currentCar;
    
    CommandTracker cmdTracker = new CommandTracker();
    
    /**
     * Creates new form ManageServiceHistoryPanel
     */
    public ManageServiceHistoryPanel() {
        initComponents();
        dpInDate.setDate(new Date());
        dpOutDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listService = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dpInDate = new org.jdesktop.swingx.JXDatePicker();
        dpOutDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAddService = new javax.swing.JButton();
        btnSaveService = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        listService.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listServiceValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listService);

        jLabel1.setText("In Date:");

        jLabel2.setText("OutDate:");

        jLabel3.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        btnAddService.setText("Add Service");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        btnSaveService.setText("Save Service");
        btnSaveService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveServiceActionPerformed(evt);
            }
        });

        btnDeleteService.setText("Delete Service");
        btnDeleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServiceActionPerformed(evt);
            }
        });

        jLabel4.setText("Service History:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddService, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveService, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteService, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dpInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dpOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dpInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dpOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddService)
                    .addComponent(btnSaveService)
                    .addComponent(btnDeleteService))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        addServiceToCar();
        clearServiceInfo();
        RefreshServiceListModel(currentCar);
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnDeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServiceActionPerformed
       
        removeServiceFromCar(listService.getSelectedValue());
        clearServiceInfo();
        RefreshServiceListModel(currentCar);
        
    }//GEN-LAST:event_btnDeleteServiceActionPerformed

    private void btnSaveServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveServiceActionPerformed
        addServiceToCar();
        removeServiceFromCar(listService.getSelectedValue());      
        clearServiceInfo();
        RefreshServiceListModel(currentCar);
    }//GEN-LAST:event_btnSaveServiceActionPerformed

    private void listServiceValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listServiceValueChanged
        if(listService.getSelectedIndex() != -1)
        {
            loadServiceInfo(listService.getSelectedValue());
        }
    }//GEN-LAST:event_listServiceValueChanged
    public void RefreshServiceListModel(Car car)
    {
        currentCar = car;
        listService.setModel(new DefaultListModel<>());
            try
            {
                ArrayList<Service> serviceHistory = currentCar.getServiceRecords();
                Collections.sort(serviceHistory, new CustomComparator());
                DefaultListModel<Service> model = new DefaultListModel<>();
                for( Service serv : serviceHistory)
                {
                    model.addElement(serv);
                }
                listService.setModel(model);
                
            }catch(Exception ex)
            {
                System.err.print(ex.getMessage());
            }
    }
    public void clearServiceInfo()
    {
        dpInDate.setDate(new Date());
        dpOutDate.setDate(new Date());
        
        txtDescription.setText("");        
    }
    public void loadServiceInfo(Service service)
    {
        dpInDate.setDate(service.getInDate());
        dpOutDate.setDate(service.getOutDate());
        
        txtDescription.setText(service.getDescription());
    }
    
    private Service createServiceFromBoxes()
    {
        return new Service(dpInDate.getDate(),dpOutDate.getDate(),txtDescription.getText());
    }
    private void addServiceToCar()
    {
        ICommandBehavior cmdBehavior = new AddService(currentCar,dpInDate.getDate(),dpOutDate.getDate(),txtDescription.getText());
        Command cmd = new Command(cmdBehavior);
        try
        {
            cmdTracker.executeCommand(cmd);
        }catch (Exception ex)
        {
            System.err.print(ex.getMessage());
        }
    }
    public void removeServiceFromCar(Service service)
    {
        if(listService.getSelectedIndex() != -1)
        {
            ICommandBehavior cmdBehavior = new RemoveService (currentCar,service);
            Command cmd = new Command(cmdBehavior);
            try
            {
                cmdTracker.executeCommand(cmd);               
            }catch(Exception ex)
            {
                
                System.err.print(ex.getMessage());
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JButton btnSaveService;
    private org.jdesktop.swingx.JXDatePicker dpInDate;
    private org.jdesktop.swingx.JXDatePicker dpOutDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Service> listService;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
